language: node_js
node_js:
  - "10.14"
before_install:
  - npm install -g typescript@3.2.2
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - dev.jeffchoi@gmail.com
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
  secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
  bucket: jeffbot-service-deploy # 6-3-3에서 생성한 S3 버킷
  region: ap-northeast-2
  skip_cleanup: true
  acl: public_read
  wait-until-deployed: true
  on:
    repo: ihello72/JeffBot #Github 주소
    branch: master